import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Test from '@/component/Three/test'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        {children}
        <div id="modal-root" />

        {/* apply temp background */}
        <Test
          style={{
            position: 'absolute',
            width: '100%',
            height: '100%',
            zIndex: -1,
          }}
        />
      </body>
    </html>
  )
}
