import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Test from '@/component/Three/test'
import Script from 'next/script'

import localFont from 'next/font/local'

const myFont = localFont({
  src: '../../public/fonts/Dovemayo_gothic.ttf',
  display: 'swap',
})
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '별이삼샵',
  description: 'Generated by create next app',
}
declare global {
  interface Window {
    Kakao: any
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr" className={myFont.className}>
      <body>
        {children}
        <div id="modal-root" />

        {/* apply temp background */}
        <Test
          style={{
            top: '0',
            position: 'absolute',
            width: '100%',
            height: '100vh',
            zIndex: -999,
          }}
        />
      </body>
      <script src="https://developers.kakao.com/sdk/js/kakao.js" async />
    </html>
  )
}
