services:

  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    volumes:
      - ./:/app/server/letter/eureka-server/
    ports:
      - 8761:8761
    expose:
      - 8761

  gateway-server:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-server
    volumes:
      - ./:/app/server/letter/gateway-server/
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - auth-service
      - letter-service
      - note-service
      - mysql

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    volumes:
      - ./:/app/server/letter/auth-service/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/letter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy106
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - mysql
      - redis

  letter-service:
    build:
      context: ./letter-service
      dockerfile: Dockerfile
    container_name: letter-service
    volumes:
      - ./:/app/server/letter/letter-service/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/letter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy106
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - mysql

  note-service:
    build:
      context: ./note-service
      dockerfile: Dockerfile
    container_name: note-service
    volumes:
      - ./:/app/server/letter/note-service/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/letter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy106
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./:/app/server/mysql/
    environment:
      MYSQL_DATABASE: letter
      MYSQL_ROOT_PASSWORD: ssafy106
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password  # 추가한 부분
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always