services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: "Asia/Seoul"  # timezone 설정 부분
    ports:
      - 80:80
    depends_on:
      - gateway-server